name: "Build and Test"

on:
  pull_request:
    branches: ['main', '3.0.x-fixes']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  
      pull-requests: read
    timeout-minutes: 130
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v3.5.0
      - name: Set up JDK 11
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Apache Maven
        run: mvn -U clean install -Djava.awt.headless=true -fae -B
    env: 
       MAVEN_OPTS: "-Xmx1024M"

